package fitnessapp;

import fitnessapp.HELPFit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author celine_yin
 */
public class HFGUIBasicDesign extends javax.swing.JFrame{
    private HELPFit hf;         // instance variable for HFGUI

    /**
     * Creates new form HFGUI
     */
    public HFGUIBasicDesign() {
        initComponents();
        setTitle("HELPFit Application");
        setSize(600, 400);
        setLocation(800, 400);
        hf = new HELPFit();             // create HELPFit object
    }
    
    /**
     * Getter for HELPFit
     */
    public HELPFit getHELPFit() {
        return hf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        memberBtn = new javax.swing.JButton();
        trainerBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pwdTF = new javax.swing.JTextField();
        logInBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newFileOption = new javax.swing.JMenuItem();
        loadFileOption = new javax.swing.JMenuItem();
        saveFileOption = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        quitOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to HELPFit!");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 21)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign Up Now:");

        memberBtn.setFont(new java.awt.Font("Verdana", 0, 21)); // NOI18N
        memberBtn.setText("Be a Member");
        memberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberBtnActionPerformed(evt);
            }
        });

        trainerBtn.setFont(new java.awt.Font("Verdana", 0, 21)); // NOI18N
        trainerBtn.setText("Be a Trainer");
        trainerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerBtnActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 21)); // NOI18N
        jLabel3.setText("Username: ");

        usernameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 21)); // NOI18N
        jLabel4.setText("Password:");

        logInBtn.setFont(new java.awt.Font("Verdana", 0, 21)); // NOI18N
        logInBtn.setText("Login");
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        newFileOption.setText("New");
        newFileOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileOptionActionPerformed(evt);
            }
        });
        jMenu1.add(newFileOption);

        loadFileOption.setText("Load");
        loadFileOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileOptionActionPerformed(evt);
            }
        });
        jMenu1.add(loadFileOption);

        saveFileOption.setText("Save");
        saveFileOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileOptionActionPerformed(evt);
            }
        });
        jMenu1.add(saveFileOption);
        jMenu1.add(jSeparator1);

        quitOption.setText("Quit");
        quitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitOptionActionPerformed(evt);
            }
        });
        jMenu1.add(quitOption);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logInBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(memberBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(trainerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(pwdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(pwdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logInBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memberBtn)
                        .addGap(44, 44, 44)
                        .addComponent(trainerBtn))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * A method to create a new HELPFit Application
     * @param evt 
     */
    private void newFileOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileOptionActionPerformed
        if (hf != null) {
            int n = JOptionPane.showConfirmDialog(this, "Would you like to save your changes first?", "Warning", JOptionPane.YES_NO_CANCEL_OPTION);
            if (n == JOptionPane.YES_OPTION)
            FileHandling.saveToFile(this, hf);
        }
        hf = new HELPFit();
        // hf.updateSequences();
    }//GEN-LAST:event_newFileOptionActionPerformed

    /**
     * A method to load HELPFit object from file
     * @param evt 
     */
    private void loadFileOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileOptionActionPerformed
        if (hf != null)               // there is an existing HELPFit object
        {
            int n = JOptionPane.showConfirmDialog(this,
                "Would you like to save your changes first?",
                "Warning", JOptionPane.YES_NO_CANCEL_OPTION);
            if (n == JOptionPane.YES_OPTION)
            FileHandling.saveToFile(this, hf);
        }
        hf = (HELPFit) FileHandling.readFromFile(this);            // downcast
        // hf.updateSequences();
    }//GEN-LAST:event_loadFileOptionActionPerformed

    /**
     * A method to save all the data of the current HELPFit Application
     * @param evt 
     */
    private void saveFileOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileOptionActionPerformed
        // call the static method in FileHandling class,
        // pass this JFrame and the
        // HELPFit object to save
        FileHandling.saveToFile(this, hf);
    }//GEN-LAST:event_saveFileOptionActionPerformed

    /**
     * A method to exit the application
     * @param evt 
     */
    private void quitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitOptionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitOptionActionPerformed

    /**
     * A method to login as a User
     * @param evt 
     */
    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        // get the values entered in the text fields
        String username = usernameTF.getText();
        String password = pwdTF.getText();

        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "You did not enter both fields.",
                "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            User theUser = hf.findUser(username);
            if (theUser == null) {
                JOptionPane.showMessageDialog(this, "There is no such username.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!theUser.getPassword().equals(password)) {
                JOptionPane.showMessageDialog(this, "The password entered is incorrect.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                /* login successful */
                // if user is a member
                if (theUser instanceof Member) {
                    Member theMember = (Member) theUser;
                    MemberMenuFrame mmFrame = new MemberMenuFrame(this, theMember);
                    mmFrame.setVisible(true);
                    this.setVisible(false);
                } else {
                    // if user is a trainer
                    TrainerMenuFrame tmFrame = new TrainerMenuFrame(this, theMember);
                    tmFrame.setVisible(true);
                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_logInBtnActionPerformed

    /**
     * A method to sign up as a Trainer when trainerBtn is clicked
     * @param evt 
     */
    private void trainerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerBtnActionPerformed
        SignUpTrainerDialog sutDialog = new SignUpTrainerDialog(this, true);
        sutDialog.setVisible(true);
    }//GEN-LAST:event_trainerBtnActionPerformed

    /**
     * A method to sign up as a Member when memberBtn is clicked
     * @param evt 
     */
    private void memberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberBtnActionPerformed
        SignUpMemberDialog sumDialog = new SignUpMemberDialog(this, true);
        sumDialog.setVisible(true);
    }//GEN-LAST:event_memberBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HFGUIBasicDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HFGUIBasicDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HFGUIBasicDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HFGUIBasicDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HFGUIBasicDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem loadFileOption;
    private javax.swing.JButton logInBtn;
    private javax.swing.JButton memberBtn;
    private javax.swing.JMenuItem newFileOption;
    private javax.swing.JTextField pwdTF;
    private javax.swing.JMenuItem quitOption;
    private javax.swing.JMenuItem saveFileOption;
    private javax.swing.JButton trainerBtn;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables

}
