/*  Compare MemberMenuDialog
 */
package fitnessapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author celine_yin
 */
public class MemberMenuFrame extends javax.swing.JFrame {
    private HELPFit helpfit;
    private HFGUI hfgui;
    private Member theMember;
    /**
     * Creates new form MemberMenuFrame
     */
    public MemberMenuFrame(HFGUI theParent, Member theMember) {
        super();
        initComponents();
        setTitle("Member Menu");
        setSize(600, 400);
        setLocation(850, 450);
        
        // make HFGUI the parent of this Frame
        hfgui = theParent;
        
        helpfit = hfgui.getHELPFit();

        // make HFGUI not visible
        hfgui.setVisible(false);
        
        this.theMember = theMember;
        // Display personalized welcome message for member
        welcomeMsgLbl.setText("Welcome, " + theMember.getFullName());
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeMsgLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editProfileBtn = new javax.swing.JButton();
        viewTrainingBtn = new javax.swing.JButton();
        viewAllSessionsBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeMsgLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcomeMsgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeMsgLbl.setText("Welcome, ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("What would you like to do?");

        editProfileBtn.setText("Edit Profile");
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });

        viewTrainingBtn.setText("View Training History");
        viewTrainingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTrainingBtnActionPerformed(evt);
            }
        });

        viewAllSessionsBtn.setText("View All Available Sessions");
        viewAllSessionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllSessionsBtnActionPerformed(evt);
            }
        });

        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(editProfileBtn)
                    .addComponent(viewTrainingBtn)
                    .addComponent(viewAllSessionsBtn)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeMsgLbl)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(editProfileBtn)
                .addGap(34, 34, 34)
                .addComponent(viewAllSessionsBtn)
                .addGap(18, 18, 18)
                .addComponent(viewTrainingBtn)
                .addGap(50, 50, 50)
                .addComponent(logOutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
        EditMemberProfileDialog empDialog = new EditMemberProfileDialog(hfgui, true, theMember);
        empDialog.setVisible(true);
    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void viewTrainingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTrainingBtnActionPerformed
        MemberTrainingHistoryDialog mthDialog = new MemberTrainingHistoryDialog(hfgui, true, theMember);
        mthDialog.setVisible(true);
    }//GEN-LAST:event_viewTrainingBtnActionPerformed

    private void viewAllSessionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllSessionsBtnActionPerformed
        UpcomingSessionsWindow usWindow = new UpcomingSessionsWindow(hfgui, true, theMember);
        usWindow.setVisible(true);
    }//GEN-LAST:event_viewAllSessionsBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        this.dispose();
        hfgui.setVisible(true);
        hfgui.setEnabled(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberMenuFrame(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton viewAllSessionsBtn;
    private javax.swing.JButton viewTrainingBtn;
    private javax.swing.JLabel welcomeMsgLbl;
    // End of variables declaration//GEN-END:variables
}
